# netlify.toml
[build]
  publish   = "."
  functions = "netlify/functions"
  # command = ""     # leave empty for a static site; uncomment & set if you actually build

[functions]
  node_bundler = "esbuild"

# Functions before SPA fallback
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

# Only keep this if you have a single-page app router (otherwise delete)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
